### ISSUE TITLE
Feature Request : Automate creation of Desktop entries

### ISSUE THREAD

**Issue by tijptjik** [malisipi/FireSSB#1]
Thank you for developing the extension and making this possible in the first place.

It would be even more amazing if the tool allowed for desktop entries (shortcuts to the SSB) to be created taking the sites favicon as the shortcut icon. Similar to how Chromium PWAs are currently handled.

In the meantime, I'd recommend adding a reference to this in the extension docs (that shows up on Mozilla) so that people know where to find the guide containing the manual instructions <3

**Comment by malisipi** [comment]
I am not sure is it possible in Windows and MacOS since their shortcut files is more complex.
However, It can be done in Linux with a few exception situation.
* I cannot access file system, so i will download the desktop entry as prefilled. However **desktop entries will not be executable by default** like any file that downloaded from internet for security reasons.
* And since i will download the desktop entry, **it would be downloaded default location** (for example, downloads folder) or trigger a file save dialog by your browser configuration.

I am not sure how can i add icon files to desktop entries. Icon parameter is supports only absolute paths and i can not access the file system. So i can not add the icon file of website to desktop entry.

Also thanks for the issue. I will try to add the feature in next release.

**Comment by malisipi** [comment]
Desktop entries can not be downloaded since they are considered as `contains illegal characters`. Also `.lnk` triggers the error like `.desktop`. Since linux has auto mimetype support without file extension, it maybe can be ignored.

![image](https://github.com/malisipi/FireSSB/assets/87281783/57b573b0-4a8f-4e00-a755-ee6245e0e14f)

**Comment by tijptjik** [comment]
FWIW - The `PWAforFirefox` project is able to automate the creation of executable `.destop` files, so perhaps worth checking out their implementation.

**Comment by malisipi** [comment]
I saw the project before, however the project requires their runtime for it near of the extension. Adding a native dependency can scare the user and browser updates can broke the dependency.
Most of features of FireSSB should be done in browser for avoiding the issues.

Also i'm drafting it (#3) for Linux. It has some missing capabilities compared to PWAforFirefox. However it has no native depency. Just install the addon and go.

If I need to explain the PR, it downloads the desktop file as prefilled.
And user give execute permission for the desktop file and moves the desktop file to applications/desktop folder or anywhere.

**Comment by malisipi** [comment]
@tijptjik Finally, desktop shortcut creation is supported in FireSSB (on Linux and Windows). You can get the version on [Mozilla Addons](https://addons.mozilla.org/en-US/firefox/addon/firessb/).

**Comment by tijptjik** [comment]
Sweet! Thanks for your continued development!
